# apiVersion: v1
# kind: Service
# metadata:
#   name: manga-harbor-service
# spec:
#   selector:
#     app: manga-harbor
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: manga-harbor-service
  labels:
    app: manga-harbor
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: manga-harbor
