apiVersion: v1
kind: Service
metadata:
  name: manga-harbor-service
  labels:
    app: manga-harbor
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32000
  selector:
    app: manga-harbor
